#!/usr/bin/env python3
import csv
RECON = {
"p021b": {
 "L001":"Gio: [...], padre di famiglia","L002":"Gasparo[?] suo fig.o",
 "L003":"Gio: [Geronimo?] suo fig.","L004":"Gio: [...] Girando[?] suo fig.o",
 "L005":"[Amierdello?] suo fig.","L006":"Gio: Batta suo fig.","L007":"Gio: [...] suo fig.",
 "L008":"Gio: [...] sua fig.","L009":"[skip]","L012":"[skip]",
 "L010":"Gio: Maria [Caleatono?] del [muorono?], padre d'famiglia",
 "L011":"Catharina moglie del ditto",
 "L013":"[...] fig. del ditto, nata ali 15 d'novembre 156[?]",
 "L014":"Gio: Ant.o fig.a del ditto, nato ali 20 d'marzo 1563",
 "L015":"Gio: Pietro fig.o del ditto, Natali 9 giugno 1574",
 "L016":"Elisabetta fig.a del ditto, nata ali 26 del 8bre 1572",
 "L017":"Gio: Gioane Gattaro[?] delli Bertig[?], padre d'famiglia",
 "L018":"[Lucina?] moglie del ditto Gioane",
 "L019":"Fran.co fig.o del ditto, nato ali 19 d'gennaro 1570",
 "L020":"Paulo fig.a del ditto, nato ali 29 d'agosto 1579",
 "L021":"Maria fig. del ditto, nata ali 2 d'febraro 1576",
},
"p022a": {
 "L001":"[...] del fibiio[?], padre de famiglia","L002":"[...] moglie del ditto",
 "L003":"[skip]","L004":"[skip]","L005":"[skip]","L006":"[skip]","L019":"[skip]","L025":"[skip]","L026":"[skip]",
 "L007":"Gioane[?] detto Batta, Nata ali 15 d'f[ebraro] [...]",
 "L008":"[...] fratello del ditto Batta","L009":"Antonia[?] sorella del ditto Bartola",
 "L010":"Matta delli Bertig[?] [Gagino?] del prato[?], padre d'famiglia",
 "L011":"Catharina moglie del ditto",
 "L012":"Gasparo[?] fig.a del ditto, nata ali 25 d'8bre 1577",
 "L013":"Gio: Maria Nepote del ditto Batta, Natali 2 d'8bre 156[?]",
 "L014":"Antonio fratello del soprascritto","L015":"Elisabetta moglie del ditto Antonio",
 "L016":"Gasparo fig.a del ditto, Natali 15 d'giugno 1568",
 "L017":"[Simono?] fig.a del ditto, nato ali [?] d'giugno 1579",
 "L018":"Margaritta fig.a del ditto, Nata 25 d'giugno 1577",
 "L020":"Gio: [...] del ditto, nato ali 25 giugno 1573",
 "L021":"Bernardo[?] fratello delli [...]","L022":"[Madalena?] moglie del ditto Bernardo",
 "L023":"Gio: Pietro fig.a del ditto, nato ali 2 d'8bre 1576",
 "L024":"Bartola fratello delli soprascritto",
},
"p022b": {
 "L001":"Gioane Gattano[?] fig.o [...] della [alhrate?], padre di famiglia",
 "L002":"[...]sina moglie del ditto Gioane",
 "L003":"[Aoranino?] fig.a del ditto, nato ali 2 d'8bre 1563",
 "L004":"Ambrosio fig.a del ditto, nato ali 12 d'giugno 156[?]",
 "L005":"Fran.co fig.a del ditto, nato ali 28 d'8bre 1570",
 "L006":"Bernardina[?] fig. del ditto, Nata 20 d'8bre 1573",
 "L007":"Jacobo Ant.o [...] Pagano[?], padre d'famiglia",
 "L008":"Angela moglie del ditto","L009":"[...] fig.a del ditto","L010":"[...] fig.o del ditto",
 "L011":"Gioane[?] Stefano fig.o del ditto",
 "L012":"Catarina fig.o del ditto, Natali 8 d'luglio 1563",
 "L013":"Gio: Batta fig.a del ditto, Natali 17 luglio 1570",
 "L014":"Gio: Ambrosio fig.o del ditto, nato ali 13 maggio 1575",
 "L015":"M[esser] Mafio[?] Cagmo[?], padre de famiglia",
 "L016":"Madona Maria moglie del ditto Mafio",
 "L017":"M[adona] Bianca[?] fig. del ditto, nata ali 15 d'febraro 1563",
 "L018":"M[adona] Margarita fig.a del ditto, nata ali 15 aprile 1564",
 "L019":"Gio: Batta fig.a del ditto, nato ali 25 aprile 1563[?]",
 "L020":"Gio: [Cristoforo?] fig.o del ditto, nato ali 2 d'8bre 1560",
 "L021":"Ludovico[?] fig. del ditto, nato ali 2 d'8bre 1560",
 "L022":"Fran.co fig.o del ditto, nato ali 12 [maggio?] 1573",
 "L023":"Costantia[?] fig. del ditto, nata ali 8 d'8bre 1575",
 "L024":"[Atacio?] fig. del ditto, Nato ali 8 del [d]ecembre 1577",
 "L025":"Catharina [...] del fig. Mafio[?]",
},
"p023a": {
 "L001":"Fran.co d'garti[?] d'[roparo?], padre d'famiglia","L002":"Angelina moglie del ditto",
 "L003":"[skip]","L004":"[skip]","L015":"[skip]","L022":"[skip]",
 "L005":"Gio: [...] del ditto, nata ali 18 d'gennaro 1[?]",
 "L006":"Gio: [...] fig.o del ditto, Nata ali 26 d'agosto 1[?]",
 "L007":"Ant.o fratello del ditto Fran.co","L008":"Gio: Maria fratello del ditto Fran.co",
 "L009":"Lucia cugnata d'ditto Fran.co",
 "L010":"Gio: Angelo fig.o d'ditta Lucia, Natali [?] d'a[prile?]",
 "L011":"Elisabetta fig.o d'ditta Lucia, Nata ali 26 d'8bre [...]",
 "L012":"Gio: Andrea d'guetto[?] d'gristoli[?], padre d'famiglia",
 "L013":"Angelina fig.o del ditto Andrea","L014":"Gio: Angelo fig.o del detto Andrea",
 "L016":"Giorgio del ditto, Nato ali 8 d'gennaro 1556",
 "L017":"Gio: Angelo Montegatio d'[agchio?] [...], padre d'famiglia",
 "L018":"Joanina moglie del ditto Gio: Angelo",
 "L019":"Elisabetta fig.a del ditto, nata ali 2 d'8bre 1569",
 "L020":"Fran.co fig.o del ditto, nato ali 14 agosto 1563",
 "L021":"Catharina fig.a del ditto, nata ali [?] d'febraro 1570",
 "L023":"Paulina madre del soprascritto Gio: Angelo [...]",
},
"p023b": {
 "L001":"Fran.co [marago?] d'Gio: Angelo del [gintilono?], padre d'famiglia",
 "L002":"Joanina moglie del ditto","L003":"Bernardino[?] fratello del Gio[...]",
 "L004":"M[esser] q. Gio: Jacobo [Cagmo?], padre de famiglia",
 "L005":"M[adona] Cecilia moglie del ditto",
 "L006":"[Baldesaro?] fig.o del ditto, Natali 28 d'8bre 1560",
 "L007":"Chiara[?] fig.a del ditto, nata ali 19 d'aprile 1572",
 "L008":"Ant.o [...] fig. del ditto, Natali 29 d'maggio 1570",
 "L009":"[Gabella?] fig.a del ditto, nata ali 28 d'8bre 1574",
 "L010":"Catarina sorella del soprascritto","L011":"Bartolanno[?] [guitorto?] del soprascritto",
 "L012":"[...] sorella del soprascritto",
 "L013":"Gio: Mat[.o?] fig.a del soprascritto [...] Gio: Pietro",
 "L014":"[Simono?] [Gatro?] [...] gennaro[?], padre d'famiglia",
 "L015":"Joanina moglie del ditto","L016":"Ant.o fig.a del ditto","L017":"Angelina fig.o del ditto",
 "L018":"Ambrosio [...]","L019":"[...] del ditto",
 "L020":"Tomasio fig. [del] ditto, Natali 16 [...] 1[?]",
 "L021":"Tomasina fig.o del ditto, nata ali [?] 17[?]",
 "L022":"[...] moglie del soprascritto [...]",
},
"p024a": {
 "L001":"Ant.o d'ghinarti[?] ditto il Pagano, padre d'famiglia",
 "L002":"[Clarga?] moglie del ditto Gio: Ant.o","L003":"Margarita fig.a d'ditto",
 "L004":"Gio: Pietro fig.o del ditto",
 "L005":"Ambrosio fig.o del ditto, nato ali 9 d'aprile 1566",
 "L006":"Tomasio fig.o della ditta Clarga","L007":"Mathio[?] fig. del soprascritto",
 "L008":"Angelona moglie del ditto Mathio","L012":"[skip]","L016":"[skip]","L022":"[skip]",
 "L009":"[...]guina fig.a del ditto, nata ali 8 d'8bre 1570",
 "L010":"[Flona?] fig.a del ditto, nata ali 26 d'gennaro 1572",
 "L011":"Fran.co fig.a del ditto, nato ali 22 d'8bre 1573",
 "L013":"[...] Batta fig.o del ditto, nato ali 14 [...] 1576",
 "L014":"Elisabetta fig.o del ditto, nata ali 23 d'8bre 1577",
 "L015":"[Ancreta?] fig.a del ditto, nata ali 17 [...]",
 "L017":"Mathio d'lagua[?] delli [malite?], padre d'famiglia",
 "L018":"[Aoneta?] moglie del ditto","L019":"Martino genero[?] d'ditto Mathio",
 "L020":"Catharina moglie d'ditto Martino","L021":"[Madmno?] fig. d'ditta Catarina",
 "L023":"Jacobo fig.o d'ditta Catharina, Nato ali 24 d'giugno [...]",
 "L024":"Paulina fig.o d'ditta Catarina, nata ali 25 marzo [...]",
},
"p024b": {
 "L001":"Ambrosio Vaccano d'quelli del [doucia?], padre d'famiglia",
 "L002":"Joanina moglie d'ditto Ambrosio",
 "L003":"Andrea fig.o d'ditto, nato ali 18 d'ottobre 1570",
 "L004":"Gio: Angelo fig.o del ditto, Natali 10 d'febraro 1575",
 "L005":"Madalena fig.a del ditto, nato ali 20 d'gennaro 1572",
 "L006":"Galiago[?] delli Arili[?] del Bertino, padre d'famiglia",
 "L007":"[Aronica?] moglie del ditto","L014":"[skip]",
 "L008":"Giorgio fig.a del ditto, nato ali 20 d'aprile 1563",
 "L009":"Matta fig.o del ditto, nato ali 16 d'8bre 156[?]",
 "L010":"Margarita fig.a del ditto, nata ali 26 d'8bre 1573",
 "L011":"Catharina fig.a del ditto, nata ali 9 d'8bre 1571",
 "L012":"Giorgio Cattano[?] d'quelli del ducia[?], padre de famiglia",
 "L013":"[Angelina?] moglie del ditto Giorgio",
 "L015":"Gio: [...] del ditto Giorgio, nata ali 20 d'giugno 1570",
 "L016":"Gio: Ambrosio fig. del ditto, nato ali 23 d'giugno 1575",
 "L017":"Catharina fig.a del ditto, nata ali 24 febraro 1571",
 "L018":"[Aamano?] d'lagua[?] [...] famiglia",
 "L019":"Elisabetta moglie del ditto",
 "L020":"Angelina fig.a del ditto, nata ali 12 d'8bre 157[?]",
},
}
for pid, fix in RECON.items():
    path=f"gold/{pid}/ensemble.tsv"
    rows=list(csv.DictReader(open(path),delimiter="\t"))
    for r in rows:
        if r["line"] in fix: r["reconciled"]=fix[r["line"]]
    with open(path,"w",newline="") as f:
        w=csv.DictWriter(f,fieldnames=rows[0].keys(),delimiter="\t"); w.writeheader(); w.writerows(rows)
    print(f"{pid}: {sum(1 for r in rows if r['reconciled']!=r['v2'])} overridden")
